(define (main)
	(display (+ 12 5))
	(newline)
	(display (+ "abc" "xyz"))
	(newline)
	(display (+ "abc" 5))
	(newline)
)
(define (main2 one two)
    (display (+ 12 5))
    (newline)
    (display (+ "abc" "xyz"))
    (newline)
    (display (+ "abc" 5))
    (newline)
)
