// Autogenerated Scheme to C++ Code
// File: test2.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object listop_ex1( )
{
	Object __RetVal;
	__RetVal = 	 a 	 b 	 c 	 d 	 e 	 f 	
	return __RetVal;
}

Object listop_ex2( )
{
	Object __RetVal;
	__RetVal = 	 a 	 b 	 c 	 d 	 e 	 f 	
	return __RetVal;
}

int main( )
{
	Object __RetVal;
	cout << listop_ex1();
	cout << listop_ex2();
	
	return 0;
}

