// Autogenerated Scheme to C++ Code
// File: test2.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object listop_ex1( )
{
 cons( listop( "car",  Object( "a b c " ) ),  listop( "cdr",  Object( "d e f " ) ) )

return __RetVal;
}

Object listop_ex2( )
{
 cons( listop( "cadr",  Object( "a b c " ) ),  listop( "cddr",  Object( "d e f " ) ) )

return __RetVal;
}

int main( )
{
cout << listop_ex1( );
cout << endl; 
 cout << listop_ex2( ); 
 cout << endl;
return 0;
}

