// Autogenerated Scheme to C++ Code
// File: ./Tests/H3oc2.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object odd_copy( ls )
{
	Object __RetVal;
	__RetVal = 	ls 	ls 	ls 	ls 	ls odd_copy(	ls )	
	return __RetVal;
}

int main( )
{
	Object __RetVal;
	cout << odd_copy(	 1 	 3 	 5 	 7 );
	cout << odd_copy(	 1 	 3 	 5 	 7 	 9 );
	
	return 0;
}

