// Autogenerated Scheme to C++ Code
// File: ./Tests/M25.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function( var )
{
	Object __RetVal;
	__RetVal = 	ls 	
	return __RetVal;
}

