// Autogenerated Scheme to C++ Code
// File: ./Tests/M4.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object functio1( var )
{
	Object __RetVal;
	__RetVal = 	* 2 2 	
	return __RetVal;
}

Object function2( var )
{
	Object __RetVal;
	__RetVal = 	* 1 1 	
	return __RetVal;
}

