// Autogenerated Scheme to C++ Code
// File: ./Tests/M65.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object abc( )
{
	Object __RetVal;
	__RetVal = 	 list? 	
	return __RetVal;
}

