// Autogenerated Scheme to C++ Code
// File: ./Tests/N25.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object a( )
{
	Object __RetVal;
	__RetVal = 	ident 	ident 	ident 	
	return __RetVal;
}

