// Autogenerated Scheme to C++ Code
// File: ./Tests/N27.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object a( )
{
	Object __RetVal;
	__RetVal = 	cons ' 	 a ' 	 b 	
	return __RetVal;
}

