// Autogenerated Scheme to C++ Code
// File: ./Tests/N33.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object a( )
{
	Object __RetVal;
	__RetVal = listP(	ident )	
	return __RetVal;
}

