// Autogenerated Scheme to C++ Code
// File: ./Tests/N59.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object reciprocal( n )
{
	Object __RetVal;
	__RetVal = ' 	 and 	
	return __RetVal;
}

