// Autogenerated Scheme to C++ Code
// File: ./Tests/N81.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object a( )
{
	Object __RetVal;
	__RetVal = 	 and 	 zero? 	 else 	
	return __RetVal;
}

