// Autogenerated Scheme to C++ Code
// File: ./Tests/P19.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object last( list )
{
	Object __RetVal;
	__RetVal = 	list 	list last(	list )	
	return __RetVal;
}

