// Autogenerated Scheme to C++ Code
// File: ./Tests/P48.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object i( )
{
	Object __RetVal;
	__RetVal = 	cout << ' 	 a ;
	
	return __RetVal;
}

