// Autogenerated Scheme to C++ Code
// File: ./Tests/P61.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object reciprocal( n )
{
	Object __RetVal;
	__RetVal = 	 not 	
	return __RetVal;
}

