// Autogenerated Scheme to C++ Code
// File: ./Tests/P64.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object symbolCheck( )
{
	Object __RetVal;
	__RetVal = 	 symbol? 	a 	
	return __RetVal;
}

