// Autogenerated Scheme to C++ Code
// File: ./Tests/Q25.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function( var )
{
	Object __RetVal;
	__RetVal = 	cond	list? 	ls "is a list" 	
	return __RetVal;
}

