// Autogenerated Scheme to C++ Code
// File: ./Tests/Q28.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function( var )
{
	Object __RetVal;
	__RetVal = AND(1 1 )	
	return __RetVal;
}

