// Autogenerated Scheme to C++ Code
// File: ./Tests/Q29.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function( var )
{
	Object __RetVal;
	__RetVal = OR()	
	return __RetVal;
}

