// Autogenerated Scheme to C++ Code
// File: ./Tests/Q30.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function( var )
{
	Object __RetVal;
	__RetVal = NOT(	== 1 1 )	
	return __RetVal;
}

