// Autogenerated Scheme to C++ Code
// File: ./Tests/Q38.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function( var )
{
	Object __RetVal;
	__RetVal = 	- 1 1 	
	return __RetVal;
}

