// Autogenerated Scheme to C++ Code
// File: ./Tests/Q39.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function( var )
{
	Object __RetVal;
	__RetVal = 	/ 4 2 	
	return __RetVal;
}

