// Autogenerated Scheme to C++ Code
// File: ./Tests/Q4.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object functio1( var )
{
	Object __RetVal;
	__RetVal = 	
	return __RetVal;
}

Object function2( var )
{
	Object __RetVal;
	__RetVal = 	
	return __RetVal;
}

