// Autogenerated Scheme to C++ Code
// File: ./Tests/Q68.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function( )
{
	Object __RetVal;
	__RetVal = ' 	 string? 	
	return __RetVal;
}

