// Autogenerated Scheme to C++ Code
// File: ./Tests/Q79.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object function( )
{
	Object __RetVal;
	__RetVal = ' 	 ' 	 a 	
	return __RetVal;
}

