// Autogenerated Scheme to C++ Code
// File: ./Tests/R24.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_24_a( )
{
	Object __RetVal;
	__RetVal = 	if	> 3 4 2 3 	
	return __RetVal;
}

Object rule_24_b( )
{
	Object __RetVal;
	__RetVal = 	if	< 3 4 ' 	 true ' 	 false 	
	return __RetVal;
}

Object rule_24_c( )
{
	Object __RetVal;
	__RetVal = 	if	null? ' ' 	 is_null ' 	 not_null 	
	return __RetVal;
}

Object rule_24_d( )
{
	Object __RetVal;
	__RetVal = 	if	zero? ' 	 3 ' 	 is_zero ' 	 not_zero 	
	return __RetVal;
}

