// Autogenerated Scheme to C++ Code
// File: ./Tests/R30.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_30_a( )
{
	Object __RetVal;
	__RetVal = 	
	return __RetVal;
}

Object rule_30_b( )
{
	Object __RetVal;
	__RetVal = 	
	return __RetVal;
}

