// Autogenerated Scheme to C++ Code
// File: ./Tests/R32.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_32_a( )
{
	Object __RetVal;
	__RetVal = 	symbol? ' 	 a 	
	return __RetVal;
}

