// Autogenerated Scheme to C++ Code
// File: ./Tests/R34.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_34_a( )
{
	Object __RetVal;
	__RetVal = 	zero? 0 	
	return __RetVal;
}

