// Autogenerated Scheme to C++ Code
// File: ./Tests/R38.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_38_a( )
{
	Object __RetVal;
	__RetVal = 	- 4 2 	
	return __RetVal;
}

