// Autogenerated Scheme to C++ Code
// File: ./Tests/R40.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_40_a( )
{
	Object __RetVal;
	__RetVal = 	* 1 2 	
	return __RetVal;
}

Object rule_40_b( )
{
	Object __RetVal;
	__RetVal = 	* 	
	return __RetVal;
}

