// Autogenerated Scheme to C++ Code
// File: ./Tests/R42.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_42_a( )
{
	Object __RetVal;
	__RetVal = 	== 2 2 	
	return __RetVal;
}

Object rule_42_b( )
{
	Object __RetVal;
	__RetVal = 	== 	
	return __RetVal;
}

