// Autogenerated Scheme to C++ Code
// File: ./Tests/R44.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_44_a( )
{
	Object __RetVal;
	__RetVal = 	
	return __RetVal;
}

Object rule_44_b( )
{
	Object __RetVal;
	__RetVal = 	
	return __RetVal;
}

