// Autogenerated Scheme to C++ Code
// File: ./Tests/R46.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_46_a( )
{
	Object __RetVal;
	__RetVal = 	<= 3 3 	
	return __RetVal;
}

Object rule_46_b( )
{
	Object __RetVal;
	__RetVal = 	<= 	
	return __RetVal;
}

