// Autogenerated Scheme to C++ Code
// File: ./Tests/R48.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule_48_a( )
{
	Object __RetVal;
	__RetVal = 	cout << "0118999\n" ;
	
	return __RetVal;
}

Object rule_48_b( )
{
	Object __RetVal;
	__RetVal = 	cout << 0118999 ;
	
	return __RetVal;
}

