// Autogenerated Scheme to C++ Code
// File: ./Tests/R76.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rules_54_71_76_a( arg1 arg2 )
{
	Object __RetVal;
	__RetVal = 	if	number? 	arg1 	if	&& 	> 	arg1 0 	list? ' 	 < 	 arg1 	 10 ' 	 cons 	 / 	 arg1 	 2 	 arg2 ' "Argument 1 should be a number\n" 	
	return __RetVal;
}

