// Autogenerated Scheme to C++ Code
// File: ./Tests/S19.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object f( )
{
	Object __RetVal;
	__RetVal = 	 modulo 	 = 	
	return __RetVal;
}

