// Autogenerated Scheme to C++ Code
// File: ./Tests/S25.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object x( )
{
	Object __RetVal;
	__RetVal = 	cond	x 	x 	
	return __RetVal;
}

