// Autogenerated Scheme to C++ Code
// File: ./Tests/S74.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object f( )
{
	Object __RetVal;
	__RetVal = 	if' 	 modulo ' 	 = 	
	return __RetVal;
}

