// Autogenerated Scheme to C++ Code
// File: ./Tests/T24.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object isList( a )
{
	Object __RetVal;
	__RetVal = 	if	list? 	a 	a ' 	 param_passed_is_not_list 	
	return __RetVal;
}

