// Autogenerated Scheme to C++ Code
// File: ./Tests/T26.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object carList( a )
{
	Object __RetVal;
	__RetVal = 	a 	
	return __RetVal;
}

