// Autogenerated Scheme to C++ Code
// File: ./Tests/T28.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object PositiveNumber( a )
{
	Object __RetVal;
	__RetVal = 	&& 	number? 	a 	<= 0 	a 	
	return __RetVal;
}

