// Autogenerated Scheme to C++ Code
// File: ./Tests/T30.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object NotList( a )
{
	Object __RetVal;
	__RetVal = 	not 	list? 	a 	
	return __RetVal;
}

