// Autogenerated Scheme to C++ Code
// File: ./Tests/T32.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object isSymbol( a )
{
	Object __RetVal;
	__RetVal = 	symbol? 	a 	
	return __RetVal;
}

