// Autogenerated Scheme to C++ Code
// File: ./Tests/T34.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object isZero( a )
{
	Object __RetVal;
	__RetVal = 	zero? 	a 	
	return __RetVal;
}

