// Autogenerated Scheme to C++ Code
// File: ./Tests/T36.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object isString( a )
{
	Object __RetVal;
	__RetVal = 	string? 	a 	
	return __RetVal;
}

