// Autogenerated Scheme to C++ Code
// File: ./Tests/T38.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object Sub( a b )
{
	Object __RetVal;
	__RetVal = 	- 	a 	b 	
	return __RetVal;
}

