// Autogenerated Scheme to C++ Code
// File: ./Tests/T42.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object EqaulTo( a b )
{
	Object __RetVal;
	__RetVal = 	a 	b 	
	return __RetVal;
}

