// Autogenerated Scheme to C++ Code
// File: ./Tests/T48.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object DisplayZ( a )
{
	Object __RetVal;
	__RetVal = 	cout << 	a ;
	
	return __RetVal;
}

