// Autogenerated Scheme to C++ Code
// File: ./Tests/T53.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object HelloWorld( )
{
	Object __RetVal;
	__RetVal = 	 HelloWorld 	
	return __RetVal;
}

