// Autogenerated Scheme to C++ Code
// File: ./Tests/T75.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object greater( )
{
	Object __RetVal;
	__RetVal = ' 	 > 	
	return __RetVal;
}

