// Autogenerated Scheme to C++ Code
// File: ./Tests/U25.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object a( )
{
	Object __RetVal;
	__RetVal = 	cond	a 	b 	c 	
	return __RetVal;
}

