// Autogenerated Scheme to C++ Code
// File: ./Tests/U43.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object greater_than( a b )
{
	Object __RetVal;
	__RetVal = 	> 	
	return __RetVal;
}

