// Autogenerated Scheme to C++ Code
// File: ./Tests/U45.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object greater_equal( a b )
{
	Object __RetVal;
	__RetVal = 	
	return __RetVal;
}

