// Autogenerated Scheme to C++ Code
// File: ./Tests/U47.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object ident( )
{
	Object __RetVal;
	__RetVal = IDENT_T()	
	return __RetVal;
}

