// Autogenerated Scheme to C++ Code
// File: ./Tests/U49.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object nwln( )
{
	Object __RetVal;
	__RetVal = NEWLINE_T()	
	return __RetVal;
}

