// Autogenerated Scheme to C++ Code
// File: ./Tests/U55.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object if_token( )
{
	Object __RetVal;
	__RetVal = 	 if 	
	return __RetVal;
}

