// Autogenerated Scheme to C++ Code
// File: ./Tests/U70.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object minus( a )
{
	Object __RetVal;
	__RetVal = ' 	 - 	
	return __RetVal;
}

