// Autogenerated Scheme to C++ Code
// File: ./Tests/U77.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object gte_token( )
{
	Object __RetVal;
	__RetVal = 	 >= 	
	return __RetVal;
}

