// Autogenerated Scheme to C++ Code
// File: ./Tests/V1.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object i( )
{
	Object __RetVal;
	__RetVal = 	i 	
	return __RetVal;
}

Object j( )
{
	Object __RetVal;
	__RetVal = 	j 	
	return __RetVal;
}

