// Autogenerated Scheme to C++ Code
// File: ./Tests/V26.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object i( )
{
	Object __RetVal;
	__RetVal = 	car 	car i()	
	return __RetVal;
}

