// Autogenerated Scheme to C++ Code
// File: ./Tests/V41.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object mod( i j )
{
	Object __RetVal;
	__RetVal = 	i 	i 	
	return __RetVal;
}

