// Autogenerated Scheme to C++ Code
// File: ./Tests/V78.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object i( )
{
	Object __RetVal;
	__RetVal = ' 	 display 	
	return __RetVal;
}

Object i( )
{
	Object __RetVal;
	__RetVal = ' 	 + 	
	return __RetVal;
}

Object i( )
{
	Object __RetVal;
	__RetVal = ' 	 <= 	
	return __RetVal;
}

