// Autogenerated Scheme to C++ Code
// File: ./Tests/W25.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule25( )
{
	Object __RetVal;
	__RetVal = 	cond	== ' 	 yeah 	
	return __RetVal;
}

