// Autogenerated Scheme to C++ Code
// File: ./Tests/W27.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule27( )
{
	Object __RetVal;
	__RetVal = const(' 	 a ' 	 b )	
	return __RetVal;
}

