// Autogenerated Scheme to C++ Code
// File: ./Tests/W31.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule31( )
{
	Object __RetVal;
	__RetVal = 	number? 0 	
	return __RetVal;
}

