// Autogenerated Scheme to C++ Code
// File: ./Tests/W33.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule33( )
{
	Object __RetVal;
	__RetVal = 	list? 0 	
	return __RetVal;
}

