// Autogenerated Scheme to C++ Code
// File: ./Tests/W35.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule35( )
{
	Object __RetVal;
	__RetVal = 	null? 0 	
	return __RetVal;
}

