// Autogenerated Scheme to C++ Code
// File: ./Tests/W41.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule41( )
{
	Object __RetVal;
	__RetVal = 	modulo 5 2 	
	return __RetVal;
}

