// Autogenerated Scheme to C++ Code
// File: ./Tests/W47.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rule47( )
{
	Object __RetVal;
	__RetVal = this()	
	return __RetVal;
}

