// Autogenerated Scheme to C++ Code
// File: ./Tests/W80.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object rules80( )
{
	Object __RetVal;
	__RetVal = 	cons ' 	 car 	cons ' 	 null? ' 	 cond 	
	return __RetVal;
}

