// Autogenerated Scheme to C++ Code
// File: ./Tests/X19.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object a( )
{
	Object __RetVal;
	__RetVal = 	if' 	 define ' 	 number? 	
	return __RetVal;
}

